version: "3.3"

services:

  main:
    build:
      context: .
      dockerfile: neo4j.dockerfile
      args:
        neo4jVersion: 5.1.0-enterprise

    environment:
      - EXTENDED_CONF=yes
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_mode=CORE

      - NEO4J_server_bolt_advertised__address=main:7687

      - NEO4J_dbms_cluster_discovery_type=DNS
      - NEO4J_dbms_cluster_minimum__initial__system__primaries__count=5
      - NEO4J_dbms_cluster_discovery_endpoints=member:5000
      
      - NEO4J_server_discovery_advertised__address=$$(/mount/ip.sh 1 5000)
      - NEO4J_server_cluster_advertised__address=$$(/mount/ip.sh 1 6000)
      - NEO4J_server_cluster_raft_advertised__address=$$(/mount/ip.sh 1 7000)
      - NEO4J_server_routing_advertised__address=$$(/mount/ip.sh 1 7688)
      
      - NEO4J_dbms_security_procedures_unrestricted=*
      
    hostname: main

    networks:
      default:
        aliases:
          - member

    volumes:
      - ./mount:/mount